# Numpy Introduction

In [2]:
import numpy as np
np.__version__

'2.2.6'

## Creating ndarrays

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

the elements of an ndarray must be of the same type (unlike python's typical lists). If types do not match, types will be upcasted if possible

In [4]:
np.array([3.14, 2, 4, 5])

array([3.14, 2.  , 4.  , 5.  ])

In [5]:
# Creating an array of zeros
display(np.zeros(10, dtype=int))

# Creating an array of ones
display(np.ones(10, dtype=float))
display(np.ones((2,5), dtype=float))

# Create a table full of the same value
display(np.full((4,2), 'a'))

# Create a ndarray similar to range() function
display(np.arange(0, 20, 2))

# Create a ndarray of some number of values evenly spaced
display(np.linspace(0, 1, 5))
display(np.linspace(0, 10, 6))

# Create an array of uniformly distributed random values between 0 and 1
display(np.random.random(5))
display(np.random.random((2,3)))

# Create an array of uniformly distributed random values of a
# normal with specific mean and stddev
display(np.random.normal(0, 1, 3))

# Create an array of random integers on a range [a, b)
display(np.random.randint(0, 10, 3))

# Create an identity matrix
display(np.eye(2))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([['a', 'a'],
       ['a', 'a'],
       ['a', 'a'],
       ['a', 'a']], dtype='<U1')

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

array([ 0.,  2.,  4.,  6.,  8., 10.])

array([0.50257461, 0.22638203, 0.08734635, 0.54461273, 0.97500567])

array([[0.90238533, 0.04137755, 0.23390072],
       [0.97723817, 0.98201029, 0.14656471]])

array([-1.35151468,  2.14607396, -0.5054587 ])

array([9, 9, 6])

array([[1., 0.],
       [0., 1.]])

### dtypes (data types)

At the creation of the `ndarray`s we can specify the type of its elements. We can specify the type via a string or via the numpy object

In [6]:
display(np.zeros(10, dtype=float))
display(np.ones(10, dtype="int16"))
display(np.zeros(5, dtype=np.int16))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

array([0, 0, 0, 0, 0], dtype=int16)

## The Basics

### Array Attributes

In [7]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

display(x1)
display(x2)
display(x3)

print(f"The array x3 has {x3.ndim} dimensions")
print(f"The shape of each dimension is {x3.shape}")
print(f"It contains a total of {x3.size} elements")
print(f"Its elements are {x3.dtype}")
print(f"It has a size of {x3.nbytes} bytes")

array([5, 0, 3, 3, 7, 9])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

The array x3 has 3 dimensions
The shape of each dimension is (3, 4, 5)
It contains a total of 60 elements
Its elements are int64
It has a size of 480 bytes


### Array indexing

In [8]:
display(x2)

print(x2[0, 0])
print(x2[0][0])
print(x2[2,-1])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

3
3
7


### Array Slicing

`x[start:stop (not included):step]`

In [9]:
display(x1)

display(x1[::])
display(x1[1::])
display(x1[:-1:])
display(x1[1:-1:2])
display(x1[::2])
display(x1[1::2])

print("\n")

display(x1[::-1])

array([5, 0, 3, 3, 7, 9])

array([5, 0, 3, 3, 7, 9])

array([0, 3, 3, 7, 9])

array([5, 0, 3, 3, 7])

array([0, 3])

array([5, 3, 7])

array([0, 3, 9])

array([9, 7, 3, 3, 0, 5])

In [10]:
# Multidimensional arrays
display(x2)

# First two rows and 3 columns
display(x2[:2, :3])

# All rows, every odd column
display(x2[:, ::2])

display(x2[::-1, ::-1])

# Accesing the first row
display(x2[0])
display(x2[0, :])

# Accesing the first column
display(x2[:, 0])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[3, 5, 2],
       [7, 6, 8]])

array([[3, 2],
       [7, 8],
       [1, 7]])

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

array([3, 5, 2, 4])

array([3, 5, 2, 4])

array([3, 7, 1])

*Note:* Slicing doesn't generates a copy of the `ndarray`, it generates a *view*. Therefore, if we modify a slice of the array, the original array is modified too:

In [11]:
display(x2)

second_col = x2[:, 1]
display(second_col)

second_col[1] = 10
display(second_col)

display(x2)

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([5, 6, 6])

array([ 5, 10,  6])

array([[ 3,  5,  2,  4],
       [ 7, 10,  8,  8],
       [ 1,  6,  7,  7]])

When we want to creat an explicit copy of the data within an array or subarray, we can use the `copy` method:

In [12]:
display(x2)
display(second_col)

second_col_cp = second_col.copy()
print("Copia realizada:")
display(second_col_cp)

second_col_cp[1] = 0
print("Modificación realizada")

display(second_col_cp)
display(second_col)

array([[ 3,  5,  2,  4],
       [ 7, 10,  8,  8],
       [ 1,  6,  7,  7]])

array([ 5, 10,  6])

Copia realizada:


array([ 5, 10,  6])

Modificación realizada


array([5, 0, 6])

array([ 5, 10,  6])

### Reshaping

In [13]:
ar = np.arange(1, 10)
display(ar)

display(ar.reshape((3, 3)))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
vec = np.array([1, 2, 3])
display(vec)

column_vec = vec.reshape((3, 1))
display(column_vec)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

### Concatenation and Splitting

In [15]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
display(np.concatenate([x, y]))

z = np.array([3, 3, 3])
display(np.concatenate([x, y, z]))

array([1, 2, 3, 3, 2, 1])

array([1, 2, 3, 3, 2, 1, 3, 3, 3])

In [16]:
# Concatenation of 2-dimensional arrays

grid = np.arange(1, 7).reshape((2, 3))
display(grid)

# Concatenate along the first axis
display(np.concatenate([grid, grid]))
display(np.concatenate([grid, grid], axis=0))

# Concatenate along the second axis
display(np.concatenate([grid, grid], axis=1))

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [17]:
# We can also use vstack and hstack (vertical/horizontal) stack
display(grid)

# Vertical
last_row = np.array([9, 9, 9])
display(np.vstack([grid, last_row]))

# Horizontal
last_col = np.array([9, 9]).reshape((2, 1))
display(np.hstack([grid, last_col]))

# dstack will stack along the third axis

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6],
       [9, 9, 9]])

array([[1, 2, 3, 9],
       [4, 5, 6, 9]])

In [18]:
# Splitting
x = np.array([1, 2, 3])
x = np.concatenate([x, z, y])
display(x)

x1, x2, x3 = np.split(x, [2, 7]) # split points
print(x1, x2, x3)

# 2-dim splitting
grid = np.arange(0, 16).reshape((4, 4))
display(grid)

upper, bottom = np.vsplit(grid, [2])
print(upper, bottom)

left, right = np.hsplit(grid, [2])
print(left, right)

array([1, 2, 3, 3, 3, 3, 3, 2, 1])

[1 2] [3 3 3 3 3] [2 1]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Universal Functions

We can perform individual operations on the whole array. It makes the syntax easier but also accelerates the code via vectorized operations.

In [19]:
numbers = np.arange(1, 6)
display(numbers)

result = np.empty(len(numbers))
for i in range(len(numbers)):
    result[i] = 1.0 / numbers[i]
display(result)

result2 = 1.0 / numbers
display(result2)

array([1, 2, 3, 4, 5])

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [20]:
# We can also operate two arrays and more than one-dimensional arrays
display(np.arange(5) / np.arange(1, 6))

x = np.arange(9).reshape((3, 3))
display(2**x)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [27]:
# The operators <, <=, >, >=, ==, != are also implemented as universal functions
# They return an array of bools:
x = np.arange(0, 11)
np.random.shuffle(x)
display(x)

comp = x > 3
display(comp)

# We can also compare two different arrays
y = np.random.choice([True, False], len(x))
display(y)

z = x == y
display(z)

array([ 5,  1,  4,  9, 10,  6,  7,  0,  3,  2,  8])

array([ True, False,  True,  True,  True,  True,  True, False, False,
       False,  True])

array([ True,  True,  True, False,  True,  True, False,  True, False,
        True,  True])

array([False,  True, False, False, False, False, False, False, False,
       False, False])

In [32]:
# We can now count the number of elements of an array given a condition with np.count_nonzero:
display(x)
print(f'There are {np.count_nonzero(x > 3)} elements on x greater than 3')

# np.sum does the same:
print(f'There are {np.sum(x > 3)} elements on x greater than 3')

# The benefit of using np.sum is that we can choose to perform the operation on all the rows/cols at once:
x = np.random.randint(10, size=(3, 4))
display(x)

# Output the number of elements of x greater than 3 on each column and on each row
print(f'There are {np.sum(x > 3, axis=0)} elements greater than 3 on each column')
print(f'There are {np.sum(x > 3, axis=1)} elements greater than 3 on each row')

array([[0, 8, 8, 3],
       [8, 2, 8, 4],
       [3, 0, 4, 3]])

There are 6 elements on x greater than 3
There are 6 elements on x greater than 3


array([[6, 9, 8, 0],
       [8, 5, 9, 0],
       [9, 6, 5, 3]])

There are [3 3 3 0] elements greater than 3 on each column
There are [3 3 3] elements greater than 3 on each row


In [ ]:
# It is helpfull to use bitwise universal operators on boolean arrays for selecting values meeting several conditions:
# Note: It is important to use | and & rather than or and "and"
display(x)

# Counting how many elements of x are on the interval [3, 6)
print(f'There are {np.sum((x >= 3) & (x < 6))} of those elements on x')

array([[6, 9, 8, 0],
       [8, 5, 9, 0],
       [9, 6, 5, 3]])

There are 3 of those elements on x


## Boolean Arrays as Masks

We can use boolean arrays as masks, in order to select the part of the arrays we are interested in

In [44]:
x = np.arange(1, 16).reshape((3,5))
display(x)

display(x > 5)

# We can form a new array with the elements we are interested in. To do that, we just need to index the array on the boolean array:
display(x[x > 5])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Fancy Indexing

In [57]:
x = np.random.randint(100, size=10)
display(x)

# Instead of doing this to work with the desired elements:
x_desired = np.array([x[1], x[3], x[7]])
display(x_desired)

# We can use fancy indexing and index the array on a list of indexes:
display(x[[1, 3, 7]])

# The indexed array reflexes the index array and not the original one. For example:
indexes = np.array([[1, 3], [7, 8]])
display(x[indexes])

array([71, 18, 92, 43, 83, 49, 41, 93, 46, 21])

array([18, 43, 93])

array([18, 43, 93])

array([[18, 43],
       [93, 46]])

In [61]:
# We can also do fancy indexing in multiple-dimension arrays:
x = np.arange(1, 16).reshape((3, 5))
display(x)

rows = [0, 1, 2]
cols = rows

display(x[rows, cols])


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

array([ 1,  7, 13])

## Exercises

In [2]:
import numpy as np

In [3]:
# 1.- Create the vector [0, ..., 19]
x = np.arange(0, 20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
# 2.- Create a 4x5 matrix of ones
x = np.ones(20).reshape((4, 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# 3.- Create an identity matrix 6x6
x = np.eye(6)
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
# 4.- Create a 5x5 matrix with random numbers between 0 and 1
x = np.random.rand(5, 5)
x

array([[0.15227322, 0.604207  , 0.03825082, 0.13123989, 0.71924038],
       [0.09275246, 0.03589487, 0.78417561, 0.87873079, 0.72202755],
       [0.28087777, 0.02792606, 0.02590676, 0.86041309, 0.96170863],
       [0.73380388, 0.69169988, 0.60187493, 0.27617859, 0.75924619],
       [0.39590315, 0.47985297, 0.10616612, 0.89017798, 0.59348568]])

In [9]:
# 5.- Transform x = np.arange(24) into a 4x6 matrix
x = np.arange(24)
x.shape = (4, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
# 6.- Extract the 3rd row of a 6x6 matrix
x = np.arange(0, 36).reshape((6, 6))
display(x)

display(x[2])

# 7.- Extract the last column of a matrix
display(x[:, -1])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

array([12, 13, 14, 15, 16, 17])

array([ 5, 11, 17, 23, 29, 35])

In [15]:
# 8.- Extract the 3x3 central block of a 5x5 matrix
x = np.arange(0, 25).reshape((5, 5))
display(x)

display(x[1:4, 1:4])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [16]:
# 9.- From x = np.arange(30) extract only the even numbers
x = np.arange(30)
display(x)
display(x[x % 2 == 0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [17]:
# 10.- Given a random array of length 100 between 0 and 1, return the elements greater than 0.8
x = np.random.rand(100)
display(len(x))

display(x[x > 0.8])

100

array([0.97922236, 0.99631326, 0.94629195, 0.89061753, 0.99569466,
       0.9043342 , 0.95858591, 0.93040674, 0.87177375, 0.83148299,
       0.98597426, 0.98432961, 0.81129841, 0.86783965, 0.80761146,
       0.82993653, 0.89958301])

In [18]:
# 11.- Given a vector [4, 7, 1, 9, 3], normalize it between 0 and 1 via:
# (x - min) / (max - min)
x = np.array([4, 7, 1, 9, 3])
y = (x - min(x)) / (max(x) - min(x))
y

array([0.375, 0.75 , 0.   , 1.   , 0.25 ])

In [22]:
# 12.- Compute the mean of each column of a matrix
x = np.arange(16).reshape((4, 4))
display(x)

display(np.mean(x, axis=0))

# 13.- Compute the stdev of each row of a matrix
display(np.std(x, axis=1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([6., 7., 8., 9.])

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [24]:
# 14.- Compute the product of two matrices
x = np.arange(12).reshape((4, 3))
y = np.arange(6).reshape((3, 2))
display(x)
display(y)

display(x @ y)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[10, 13],
       [28, 40],
       [46, 67],
       [64, 94]])

In [ ]:
from math import sqrt
# 15.- Compute the Euclides distance between two vectors
x = np.arange(1, 4)
y = np.arange(4, 9, 2)
display(x)
display(y)

dist = sqrt(np.sum((x-y)**2))
dist

array([1, 2, 3])

array([4, 6, 8])

7.0710678118654755

In [33]:
# 16.- Given a matrix, for each column subtract its mean
x = np.arange(20).reshape((4, 5))
display(x)

display(np.mean(x, axis=0))

display(x - np.mean(x, axis=0))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

array([[-7.5, -7.5, -7.5, -7.5, -7.5],
       [-2.5, -2.5, -2.5, -2.5, -2.5],
       [ 2.5,  2.5,  2.5,  2.5,  2.5],
       [ 7.5,  7.5,  7.5,  7.5,  7.5]])

In [36]:
# 17.- Multiply each row of a matrix by different scalars
factors = np.arange(1, 5)
display(factors)

x = np.arange(16).reshape((4, 4))
display(x)

display(x * factors[:, np.newaxis])

array([1, 2, 3, 4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  1,  2,  3],
       [ 8, 10, 12, 14],
       [24, 27, 30, 33],
       [48, 52, 56, 60]])

In [ ]:
# 18.- Given two arrays of points A and B, compute the distance between each point of A and each point of B

In [42]:
# 19.- Given a vector, transform it into a One-Hot matrix
x = np.array([2, 0, 1, 2, 1])

# Option 1. Indexing the 3-identity matrix
y = np.eye(3)[x]
display(y)

# Option 2. 
options = x.max() + 1
one_hot = np.zeros((len(x), options), dtype=int)
one_hot[np.arange(len(x)), x] = 1
display(one_hot)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [43]:
# 20.- Z-Score normalization. Normalize using (x - mean) / stdev
x = np.arange(10)
display(x)

display((x - np.mean(x)) / np.std(x))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [44]:
# 21.- Transpose a matrix
x = np.arange(12).reshape((3, 4))
display(x)

display(x.T)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])