# Numpy Introduction

In [2]:
import numpy as np
np.__version__

'2.2.6'

## Creating ndarrays

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

the elements of an ndarray must be of the same type (unlike python's typical lists). If types do not match, types will be upcasted if possible

In [4]:
np.array([3.14, 2, 4, 5])

array([3.14, 2.  , 4.  , 5.  ])

In [25]:
# Creating an array of zeros
display(np.zeros(10, dtype=int))

# Creating an array of ones
display(np.ones(10, dtype=float))
display(np.ones((2,5), dtype=float))

# Create a table full of the same value
display(np.full((4,2), 'a'))

# Create a ndarray similar to range() function
display(np.arange(0, 20, 2))

# Create a ndarray of some number of values evenly spaced
display(np.linspace(0, 1, 5))
display(np.linspace(0, 10, 6))

# Create an array of uniformly distributed random values between 0 and 1
display(np.random.random(5))
display(np.random.random((2,3)))

# Create an array of uniformly distributed random values of a
# normal with specific mean and stddev
display(np.random.normal(0, 1, 3))

# Create an array of random integers on a range [a, b)
display(np.random.randint(0, 10, 3))

# Create an identity matrix
display(np.eye(2))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([['a', 'a'],
       ['a', 'a'],
       ['a', 'a'],
       ['a', 'a']], dtype='<U1')

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

array([ 0.,  2.,  4.,  6.,  8., 10.])

array([0.61173118, 0.06691201, 0.6291956 , 0.7366585 , 0.69094696])

array([[0.83413493, 0.1053861 , 0.36824308],
       [0.17530552, 0.68446264, 0.72085115]])

array([ 1.47267934,  1.18236434, -0.50086172])

array([6, 1, 5])

array([[1., 0.],
       [0., 1.]])

### dtypes (data types)

At the creation of the `ndarray`s we can specify the type of its elements. We can specify the type via a string or via the numpy object

In [29]:
display(np.zeros(10, dtype=float))
display(np.ones(10, dtype="int16"))
display(np.zeros(5, dtype=np.int16))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

array([0, 0, 0, 0, 0], dtype=int16)

## The Basics

### Array Attributes

In [35]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

display(x1)
display(x2)
display(x3)

print(f"The array x3 has {x3.ndim} dimensions")
print(f"The shape of each dimension is {x3.shape}")
print(f"It contains a total of {x3.size} elements")
print(f"Its elements are {x3.dtype}")
print(f"It has a size of {x3.nbytes} bytes")

array([5, 0, 3, 3, 7, 9])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

The array x3 has 3 dimensions
The shape of each dimension is (3, 4, 5)
It contains a total of 60 elements
Its elements are int64
It has a size of 480 bytes


### Array indexing

In [40]:
display(x2)

print(x2[0, 0])
print(x2[0][0])
print(x2[2,-1])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

3
3
7


### Array Slicing

`x[start:stop (not included):step]`

In [ ]:
display(x1)

display(x1[::])
display(x1[1::])
display(x1[:-1:])
display(x1[1:-1:2])
display(x1[::2])
display(x1[1::2])

print("\n")

display(x1[::-1])

array([5, 0, 3, 3, 7, 9])

array([5, 0, 3, 3, 7, 9])

array([0, 3, 3, 7, 9])

array([5, 0, 3, 3, 7])

array([0, 3])

array([5, 3, 7])

array([0, 3, 9])

array([9, 7, 3, 3, 0, 5])

array([9, 7, 3, 3, 0])

In [60]:
# Multidimensional arrays
display(x2)

# First two rows and 3 columns
display(x2[:2, :3])

# All rows, every odd column
display(x2[:, ::2])

display(x2[::-1, ::-1])

# Accesing the first row
display(x2[0])
display(x2[0, :])

# Accesing the first column
display(x2[:, 0])

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[3, 5, 2],
       [7, 6, 8]])

array([[3, 2],
       [7, 8],
       [1, 7]])

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

array([3, 5, 2, 4])

array([3, 5, 2, 4])

array([3, 7, 1])

*Note:* Slicing doesn't generates a copy of the `ndarray`, it generates a *view*. Therefore, if we modify a slice of the array, the original array is modified too:

In [66]:
display(x2)

second_col = x2[:, 1]
display(second_col)

second_col[1] = 10
display(second_col)

display(x2)

array([[ 3,  5,  2,  4],
       [ 7, 10,  8,  8],
       [ 1,  6,  7,  7]])

array([ 5, 10,  6])

array([ 5, 10,  6])

array([[ 3,  5,  2,  4],
       [ 7, 10,  8,  8],
       [ 1,  6,  7,  7]])

When we want to creat an explicit copy of the data within an array or subarray, we can use the `copy` method:

In [72]:
display(x2)
display(second_col)

second_col_cp = second_col.copy()
print("Copia realizada:")
display(second_col_cp)

second_col_cp[1] = 0
print("Modificación realizada")

display(second_col_cp)
display(second_col)

array([[ 3,  5,  2,  4],
       [ 7, 10,  8,  8],
       [ 1,  6,  7,  7]])

array([ 5, 10,  6])

Copia realizada:


array([ 5, 10,  6])

Modificación realizada


array([5, 0, 6])

array([ 5, 10,  6])

### Reshaping

In [81]:
ar = np.arange(1, 10)
display(ar)

display(ar.reshape((3, 3)))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
vec = np.array([1, 2, 3])
display(vec)

column_vec = vec.reshape((3, 1))
display(column_vec)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

### Concatenation and Splitting